  This file belongs to the CWEB-NLS package.

  Fonts
:1:cmr9
:2:cmr8
:3:cmss10
:4:cmr7
:5:cmtt10
:6:cmtex10
:7:cmtt10
  Redefine \postATl and \ATH
:8:\bf letter \\{\uppercase{\char"#1}} tangles as \tentex "#2"
:9:Preprocessor definitions
  Redefine \A -- \ch
:10:See also section
:11:See also sections
:12: and
:13:, and
:14:format
:15:This code is cited in section
:16:This code is cited in sections
:17:This code is used in section
:18:This code is used in sections
:19:\.{CWEB} output
:20:The following sections were changed by the change file:
  Redefine \inx
:21:Index:
  Redefine \fin
:22:NAMES OF THE SECTIONS
:23:Section names:
:24:Cited in section
:25:Cited in sections
:26:Used in section
:27:Used in sections
  Redefine \con..
:28:Names of the sections
:29:TABLE OF CONTENTS
:30:Table of contents:
:31:Section
:32:Page
  Redefine \today
:33:January
:34:February
:35:March
:36:April
:37:May
:38:June
:39:July
:40:August
:41:September
:42:October
:43:November
:44:December
  Redefine \datethis and \datecontentspage
:45:at
