  This file belongs to the CWEB-NLS package.

  Fonts
:1:plr9
:2:plr8
:3:plss10
:4:plr7
:5:pltt10
:6:pltex10
:7:pltt10
  Redefine \postATl and \ATH
:8:(zobacz \jobname.tex)
:9:Definicje dla preprocesora
  Redefine \A -- \ch
:10:Kontynuacja: sekcja
:11:Kontynuacja: sekcje
:12: i
:13: i
:14:format
:15:Ten kod jest cytowany w sekcji
:16:Ten kod jest cytowany w sekcjach
:17:Ten kod jest u¿yty w sekcji
:18:Ten kod jest u¿yty w sekcjach
:19:cweb-pl output
:20:Nastêpuj±ce sekcje uleg³y aktualizacji przez plik zmian:
  Redefine \inx
:21:Indeks:
  Redefine \fin
:22:NAZWY SEKCJI
:23:Nazwy sekcji:
:24:Cytowano w sekcji
:25:Cytowano w sekcjach
:26:U¿yto w sekcji
:27:U¿yto w sekcjach
  Redefine \con..
:28:Nazwy sekcji
:29:SPIS TRE¦CI
:30:Spis tre¶ci:
:31:Sekcja
:32:Strona
  Redefine \today
:33:Styczeñ
:34:Luty
:35:Marzec
:36:Kwiecieñ
:37:Maj
:38:Czerwiec
:39:Lipiec
:40:Sierpieñ
:41:Wrzesieñ
:42:Pa¼dziernik
:43:Listopad
:44:Grudzieñ
  Redefine \datethis and \datecontentspage
:45:godzina 
